### ISSUE TITLE
pairing key encoding/hex: invalid byte 

### ISSUE THREAD

**Issue by 3esmit** [keycard-tech/keycard-cli#11]
I am unable to access my keycard using this software. When I enter my pairing code it gives this error:

`encoding/hex: invalid byte:` and the first letter of the pairing key.

Seems like its expecting me to enter it in hexadecimal. Why not accept plain text, as this is what humans use?

**Comment by gravityblast** [comment]
hey @3esmit !! we updated the code and removed the pairing command in favour of shell scripts, that you can find in the `_shell-commands-examples` folder.
In the future I will add a way to save the pairing key somewhere but for now I think it's better to have a script that does `pair/something/unpair`.
