### ISSUE TITLE
keycard-generate-mnemonic not found

### ISSUE THREAD

**Issue by willianpaixao** [keycard-tech/keycard-cli#12]
Having the script file `generate-mnemonic.sh`:
```
keycard-select
keycard-set-secrets 123456 12345678 abcdefg
keycard-pair

keycard-open-secure-channel
keycard-verify-pin {{ session_pin }}

keycard-generate-mnemonic
```
Then run:
```sh
keycard shell -l debug < generate-mnemonic.sh
```
Gives an error.
``` sh
ERROR[12-02|20:31:58.447] error executing command                  package=status-go/cmd/keycard command=shell error="command not found: keycard-generate-mnemonic"
```

**Comment by bitgamma** [comment]
keycard-generate-mnemonic takes the checksum size as a parameter. Please check _shell-commands-examples.

**Comment by willianpaixao** [comment]
Still, why throw a `command not found`?

For `commandKeycardSignMessagePinless` there's a check:
```go
if len(args) < 1 {
    return errors.New("keycard-sign-message-pinless require at least 1 parameter")
}
```

**Comment by bitgamma** [comment]
are you trying the released build or building from source? building from source works are you described.

PS: there will be a new release soon

**Comment by willianpaixao** [comment]
No, I was using the latest official release. But I can wait for the next release and try again.
