### ISSUE TITLE
keycard CLI 64 bits windows installer detected as a potential virus by virus total 

### ISSUE THREAD

**Issue by cryptoanalyzers2** [keycard-tech/keycard-cli#22]
![image](https://github.com/status-im/keycard-cli/assets/45768987/73db53c5-4184-4a63-93ef-d18a8f99bd80)

This is what virus total displays when the installer is scanned (keycard-windows-amd64.exe) 
The date: 14 November 2023

Either it is a false positive, or somehow a tampered version is present in the download website. 
5 AVs that detects the presence on a virus in virus total is 7% which is already not a simple problem. (usually on virus total a false positive is a virus detection by just one AV )

**Comment by bitgamma** [comment]
these are false positives, most likely given by the combination of the software not being well-known to antiviruses, use of encryption API and access to system APIs (smartcard API). The file is btw not an installer, it is the actual tool.
