### ISSUE TITLE
Applet AID mismatch between CLI and cap file

### ISSUE THREAD

**Issue by cryptoanalyzers2** [keycard-tech/keycard-cli#23]
The CLI expects the applets to have AIDS : 

A0 00 00 08 04 00 01 01 01
A0 00 00 08 04 00 01 02 01
A0 00 00 08 04 00 01 03 01
A0 00 00 08 04 00 01 04 01

But the CAP file distributed by keycard (https://github.com/status-im/keycard-cli/releases) 
is configured in such a way that the applets will have the following AIDs when they are installed:

A0 00 00 08 04 00 01 01 
A0 00 00 08 04 00 01 02 
A0 00 00 08 04 00 01 03 
A0 00 00 08 04 00 01 04 

eg without the last '01'

As a result keycard CLI cannot interface the card

```
[32mINFO ←[0m[11-17|08:58:33.615] select keycard applet                    ←[32mpackage←[0m=keycard-cli
←[36mDEBUG←[0m[11-17|08:58:33.618] apdu command                             ←[36mpackage←[0m=keycard-go/io ←[36mhex←[0m="00 A4 04 00 09 A0 00 00 08 04 00 01 01 01 00"
←[36mDEBUG←[0m[11-17|08:58:33.641] apdu response                            ←[36mpackage←[0m=keycard-go/io ←[36mhex←[0m="6A 82"
←[32mINFO ←[0m[11-17|08:58:33.641] select cash applet                       ←[32mpackage←[0m=keycard-cli
←[36mDEBUG←[0m[11-17|08:58:33.643] apdu command                             ←[36mpackage←[0m=keycard-go/io ←[36mhex←[0m="00 A4 04 00 09 A0 00 00 08 04 00 01 03 01 00"
←[36mDEBUG←[0m[11-17|08:58:33.659] apdu response                            ←[36mpackage←[0m=keycard-go/io ←[36mhex←[0m="6A 82"
```

There doesn't seem to have any way to configure the keycard CLI to change the AIDs (eg they are hardcoded)

**Comment by cryptoanalyzers2** [comment]
note: I recompiled the applet to have the AIDs matching and now that works fine.

**Comment by bitgamma** [comment]
the AIDs expected by the CLI are the same we use on actual keycards. Note tha the AID in the cap file (Class AID) and the AID of the installed applet (Instance AID) do not have to match. Indeed we add a "01" to indicate the first instance (you can install the same applet multiple times).

**Comment by cryptoanalyzers2** [comment]
true that several instances can be used from the package (load file) and module and that the applet instance doesn't have necessarily to coincide with the module AID however that can create an issue with some tools when the applet is instantiated outside the CLI . In all cases, as a suggestion, these AIDs should be documented somewhere and especially the fact that the applet AID is different from the module AID.
